apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels: 
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: host
          value: "database"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "devopsdb"
        ports:
        - containerPort: 5432  